# Generated by Django 6.0.4 on 2026-05-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='total_chapters',
            new_name='total_units',
        ),
        migrations.AlterField(
            model_name='subject',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
